import React, { useState } from 'react';
import { 
  CheckCircle2, 
  AlertTriangle, 
  XCircle, 
  Target, 
  FileText, 
  Copy, 
  Check, 
  Layers, 
  Download, 
  TrendingUp,
  Search,
  Printer,
  FileCheck,
  CheckCircle
} from 'lucide-react';
import { AnalysisResult } from '../types';

interface AnalysisResultsProps {
  analysis: AnalysisResult;
  onOpenJobMatch: () => void;
  onOpenCoverLetter: () => void;
  onOpenInterviewPrep: () => void;
}

export const AnalysisResults: React.FC<AnalysisResultsProps> = ({
  analysis,
  onOpenJobMatch,
  onOpenCoverLetter,
  onOpenInterviewPrep,
}) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'atsChecks' | 'sections' | 'skills' | 'actionPlan'>('overview');
  const [copiedIndex, setCopiedIndex] = useState<string | null>(null);
  const [skillSearch, setSkillSearch] = useState('');
  const [atsFilter, setAtsFilter] = useState<'all' | 'warning' | 'fail' | 'pass'>('all');
  const [showExportToast, setShowExportToast] = useState(false);

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(id);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const getGrade = (score: number) => {
    if (score >= 90) return { grade: 'A+', label: 'Strong Pass', passRate: 'High ATS Compatibility' };
    if (score >= 80) return { grade: 'A', label: 'Pass', passRate: 'Compatible with Standard ATS' };
    if (score >= 70) return { grade: 'B+', label: 'Moderate', passRate: 'Minor Keyword / Format Gaps' };
    if (score >= 60) return { grade: 'C', label: 'Needs Optimization', passRate: 'Potential Parsing Bottlenecks' };
    return { grade: 'D', label: 'At Risk', passRate: 'High Risk of ATS Rejection' };
  };

  const gradeInfo = getGrade(analysis.overallScore);

  const handleExportReport = () => {
    const report = `# RESUMIND — RESUME & ATS AUDIT REPORT
Document: ${analysis.pdfMeta?.filename || 'Resume'}
Overall ATS Score: ${analysis.overallScore}/100 (Grade: ${gradeInfo.grade} - ${gradeInfo.label})
ATS Parsability: ${analysis.atsScore}/100
Impact & Metric Quantification: ${analysis.impactScore}/100
Keyword Density: ${analysis.keywordScore}/100
Format & Layout: ${analysis.formattingScore}/100

## EXECUTIVE SUMMARY
${analysis.summary}

## KEY STRENGTHS
${analysis.keyStrengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

## CRITICAL GAPS & RISKS
${analysis.criticalGaps.map((g, i) => `${i + 1}. ${g}`).join('\n')}

## ACTIONABLE NEXT STEPS
${analysis.actionableNextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

---
Generated by ResuMind Audit Platform.
Contact: Tathagata Chakraborty (tathagatachakraborty1234@gmail.com)
`;
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(analysis.pdfMeta?.filename || 'Resume').replace('.pdf', '')}_ATS_Audit_Report.md`;
    a.click();
    URL.revokeObjectURL(url);
    setShowExportToast(true);
    setTimeout(() => setShowExportToast(false), 3000);
  };

  const handlePrint = () => {
    window.print();
  };

  const filteredAtsChecks = analysis.atsChecks.filter((c) => {
    if (atsFilter === 'all') return true;
    return c.status === atsFilter;
  });

  return (
    <div className="w-full space-y-5 animate-fade-in">
      
      {/* Toast notification on report export */}
      {showExportToast && (
        <div className="fixed bottom-6 right-6 z-50 bg-slate-900 dark:bg-slate-100 text-white dark:text-slate-900 px-4 py-2.5 rounded-lg shadow-lg flex items-center space-x-2 text-xs font-semibold animate-fade-in">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 dark:text-emerald-600" />
          <span>Report exported as Markdown (.md)</span>
        </div>
      )}

      {/* 1. Scorecard Card */}
      <div className="bg-white dark:bg-[#0f0f0f] border border-slate-200/80 dark:border-slate-800 rounded-2xl p-5 sm:p-6 transition-colors shadow-xs">
        
        {/* Header Ribbon */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-5 border-b border-slate-100 dark:border-slate-800">
          <div>
            <div className="flex items-center space-x-2">
              <span className="px-2.5 py-0.5 text-[10px] font-bold uppercase bg-[#DBEAFE] text-[#1D4ED8] dark:bg-blue-950/70 dark:text-blue-300 rounded-md">
                Audit Completed
              </span>
              <span className="text-xs text-slate-400 dark:text-slate-500">•</span>
              <span className="text-xs font-semibold text-[#64748B] dark:text-slate-300 truncate max-w-[220px] sm:max-w-xs">
                {analysis.pdfMeta?.filename || 'Uploaded Resume'}
              </span>
            </div>
            <h2 className="text-xl font-bold text-[#0F172A] dark:text-white mt-1.5">
              ATS Compatibility & Content Scorecard
            </h2>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleExportReport}
              className="px-3 py-1.5 bg-[#F8FAFC] dark:bg-slate-800 hover:bg-slate-200/70 dark:hover:bg-slate-700 text-[#334155] dark:text-slate-200 font-semibold text-xs rounded-lg border border-slate-200/80 dark:border-slate-700 flex items-center space-x-1.5 transition-colors cursor-pointer shadow-2xs"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Report</span>
            </button>

            <button
              onClick={handlePrint}
              className="p-2 bg-[#F8FAFC] dark:bg-slate-800 hover:bg-slate-200/70 dark:hover:bg-slate-700 text-[#334155] dark:text-slate-200 rounded-lg border border-slate-200/80 dark:border-slate-700 transition-colors cursor-pointer hidden sm:block"
              title="Print scorecard"
            >
              <Printer className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        {/* Score Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-center pt-5">
          
          {/* Main Score Gauge */}
          <div className="lg:col-span-4 flex flex-col items-center justify-center p-5 bg-[#F8FAFC] dark:bg-[#161616] rounded-xl border border-slate-200/80 dark:border-slate-800 text-center">
            
            <div className="relative w-28 h-28 flex items-center justify-center">
              <svg className="w-full h-full -rotate-90" viewBox="0 0 120 120">
                <circle
                  cx="60"
                  cy="60"
                  r="52"
                  className="stroke-slate-200 dark:stroke-slate-700"
                  strokeWidth="8"
                  fill="transparent"
                />
                <circle
                  cx="60"
                  cy="60"
                  r="52"
                  className={analysis.overallScore >= 80 ? 'stroke-[#16A34A]' : analysis.overallScore >= 60 ? 'stroke-[#D97706]' : 'stroke-rose-500'}
                  strokeWidth="8"
                  strokeDasharray={326.7}
                  strokeDashoffset={326.7 - (326.7 * analysis.overallScore) / 100}
                  strokeLinecap="round"
                  fill="transparent"
                />
              </svg>

              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className="text-3xl font-extrabold font-mono text-[#0F172A] dark:text-white tracking-tight">
                  {analysis.overallScore}
                </span>
                <span className="text-[10px] font-bold text-[#64748B] dark:text-slate-400 uppercase tracking-widest">
                  / 100
                </span>
              </div>
            </div>

            <div className="mt-3 space-y-1">
              <div className={`inline-flex items-center space-x-1.5 px-2.5 py-0.5 rounded-md text-xs font-semibold border ${
                analysis.overallScore >= 80
                  ? 'bg-emerald-50 dark:bg-emerald-950/70 text-[#16A34A] dark:text-emerald-300 border-emerald-200 dark:border-emerald-800'
                  : analysis.overallScore >= 60
                  ? 'bg-amber-50 dark:bg-amber-950/70 text-[#D97706] dark:text-amber-300 border-amber-200 dark:border-amber-800'
                  : 'bg-rose-50 dark:bg-rose-950/70 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800'
              }`}>
                <span>Grade: {gradeInfo.grade}</span>
                <span>•</span>
                <span>{gradeInfo.label}</span>
              </div>
              <p className="text-xs text-[#64748B] dark:text-slate-400 font-normal">
                {gradeInfo.passRate}
              </p>
            </div>
          </div>

          {/* Metrics Matrix & Summary */}
          <div className="lg:col-span-8 space-y-4">
            <div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-[#64748B] dark:text-slate-400 mb-1">
                Executive Synthesis
              </h3>
              <p className="text-xs sm:text-sm text-[#334155] dark:text-slate-300 leading-relaxed font-normal">
                {analysis.summary}
              </p>
            </div>

            {/* 4 Dimension Matrix */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
              
              <div className="bg-[#F8FAFC] dark:bg-[#161616] p-3 rounded-xl border border-slate-200/80 dark:border-slate-800 space-y-1.5">
                <span className="text-[10px] text-[#64748B] dark:text-slate-400 uppercase font-bold tracking-wider block">ATS Parsing</span>
                <div className="flex items-baseline justify-between">
                  <span className="text-lg font-bold font-mono text-[#0F172A] dark:text-white tracking-tight">{analysis.atsScore}%</span>
                </div>
                <div className="w-full bg-slate-200 dark:bg-slate-700 h-1.5 rounded-full overflow-hidden">
                  <div className={`h-full rounded-full ${analysis.atsScore >= 80 ? 'bg-[#16A34A]' : analysis.atsScore >= 60 ? 'bg-[#D97706]' : 'bg-rose-500'}`} style={{ width: `${analysis.atsScore}%` }} />
                </div>
              </div>

              <div className="bg-[#F8FAFC] dark:bg-[#161616] p-3 rounded-xl border border-slate-200/80 dark:border-slate-800 space-y-1.5">
                <span className="text-[10px] text-[#64748B] dark:text-slate-400 uppercase font-bold tracking-wider block">Impact & Metric</span>
                <div className="flex items-baseline justify-between">
                  <span className="text-lg font-bold font-mono text-[#0F172A] dark:text-white tracking-tight">{analysis.impactScore}%</span>
                </div>
                <div className="w-full bg-slate-200 dark:bg-slate-700 h-1.5 rounded-full overflow-hidden">
                  <div className={`h-full rounded-full ${analysis.impactScore >= 80 ? 'bg-[#16A34A]' : analysis.impactScore >= 60 ? 'bg-[#D97706]' : 'bg-rose-500'}`} style={{ width: `${analysis.impactScore}%` }} />
                </div>
              </div>

              <div className="bg-[#F8FAFC] dark:bg-[#161616] p-3 rounded-xl border border-slate-200/80 dark:border-slate-800 space-y-1.5">
                <span className="text-[10px] text-[#64748B] dark:text-slate-400 uppercase font-bold tracking-wider block">Content Depth</span>
                <div className="flex items-baseline justify-between">
                  <span className="text-lg font-bold font-mono text-[#0F172A] dark:text-white tracking-tight">{analysis.contentScore}%</span>
                </div>
                <div className="w-full bg-slate-200 dark:bg-slate-700 h-1.5 rounded-full overflow-hidden">
                  <div className={`h-full rounded-full ${analysis.contentScore >= 80 ? 'bg-[#16A34A]' : analysis.contentScore >= 60 ? 'bg-[#D97706]' : 'bg-rose-500'}`} style={{ width: `${analysis.contentScore}%` }} />
                </div>
              </div>

              <div className="bg-[#F8FAFC] dark:bg-[#161616] p-3 rounded-xl border border-slate-200/80 dark:border-slate-800 space-y-1.5">
                <span className="text-[10px] text-[#64748B] dark:text-slate-400 uppercase font-bold tracking-wider block">Role Keywords</span>
                <div className="flex items-baseline justify-between">
                  <span className="text-lg font-bold font-mono text-[#0F172A] dark:text-white tracking-tight">{analysis.keywordScore}%</span>
                </div>
                <div className="w-full bg-slate-200 dark:bg-slate-700 h-1.5 rounded-full overflow-hidden">
                  <div className={`h-full rounded-full ${analysis.keywordScore >= 80 ? 'bg-[#16A34A]' : analysis.keywordScore >= 60 ? 'bg-[#D97706]' : 'bg-rose-500'}`} style={{ width: `${analysis.keywordScore}%` }} />
                </div>
              </div>

            </div>

            {/* Action Shortcuts */}
            <div className="flex flex-wrap items-center gap-2 pt-1">
              <button
                onClick={onOpenJobMatch}
                className="px-3.5 py-2 bg-[#2563EB] hover:bg-blue-700 text-white font-semibold text-xs rounded-xl transition-all shadow-xs flex items-center space-x-1.5 cursor-pointer"
              >
                <Target className="w-3.5 h-3.5" />
                <span>Tailor to Job Description</span>
              </button>

              <button
                onClick={onOpenCoverLetter}
                className="px-3.5 py-2 bg-[#F8FAFC] dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-[#334155] dark:text-slate-200 font-semibold text-xs rounded-xl border border-slate-200/80 dark:border-slate-700 flex items-center space-x-1.5 transition-colors cursor-pointer"
              >
                <FileText className="w-3.5 h-3.5" />
                <span>Draft Cover Letter</span>
              </button>

              <button
                onClick={onOpenInterviewPrep}
                className="px-3.5 py-2 bg-[#F8FAFC] dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-[#334155] dark:text-slate-200 font-semibold text-xs rounded-xl border border-slate-200/80 dark:border-slate-700 flex items-center space-x-1.5 transition-colors cursor-pointer"
              >
                <TrendingUp className="w-3.5 h-3.5" />
                <span>Interview Q&A Guide</span>
              </button>
            </div>

          </div>

        </div>
      </div>

      {/* 2. Navigation Tabs */}
      <div className="flex bg-[#F8FAFC] dark:bg-[#121212] p-1 rounded-xl border border-slate-200/80 dark:border-slate-800 overflow-x-auto space-x-1 scrollbar-none">
        <button
          onClick={() => setActiveTab('overview')}
          className={`px-3.5 py-2 rounded-lg text-xs font-semibold whitespace-nowrap transition-all flex items-center space-x-1.5 cursor-pointer ${
            activeTab === 'overview'
              ? 'bg-white dark:bg-slate-800 text-[#2563EB] dark:text-blue-400 shadow-2xs'
              : 'text-[#334155] dark:text-slate-400 hover:text-[#0F172A] dark:hover:text-white'
          }`}
        >
          <FileCheck className="w-3.5 h-3.5" />
          <span>Strengths & Gaps</span>
        </button>

        <button
          onClick={() => setActiveTab('atsChecks')}
          className={`px-3.5 py-2 rounded-lg text-xs font-semibold whitespace-nowrap transition-all flex items-center space-x-1.5 cursor-pointer ${
            activeTab === 'atsChecks'
              ? 'bg-white dark:bg-slate-800 text-[#2563EB] dark:text-blue-400 shadow-2xs'
              : 'text-[#334155] dark:text-slate-400 hover:text-[#0F172A] dark:hover:text-white'
          }`}
        >
          <span>ATS Checklist ({analysis.atsChecks.length})</span>
        </button>

        <button
          onClick={() => setActiveTab('sections')}
          className={`px-3.5 py-2 rounded-lg text-xs font-semibold whitespace-nowrap transition-all flex items-center space-x-1.5 cursor-pointer ${
            activeTab === 'sections'
              ? 'bg-white dark:bg-slate-800 text-[#2563EB] dark:text-blue-400 shadow-2xs'
              : 'text-[#334155] dark:text-slate-400 hover:text-[#0F172A] dark:hover:text-white'
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          <span>Section Review & Rewrites</span>
        </button>

        <button
          onClick={() => setActiveTab('skills')}
          className={`px-3.5 py-2 rounded-lg text-xs font-semibold whitespace-nowrap transition-all flex items-center space-x-1.5 cursor-pointer ${
            activeTab === 'skills'
              ? 'bg-white dark:bg-slate-800 text-[#2563EB] dark:text-blue-400 shadow-2xs'
              : 'text-[#334155] dark:text-slate-400 hover:text-[#0F172A] dark:hover:text-white'
          }`}
        >
          <span>Extracted Skills</span>
        </button>

        <button
          onClick={() => setActiveTab('actionPlan')}
          className={`px-3.5 py-2 rounded-lg text-xs font-semibold whitespace-nowrap transition-all flex items-center space-x-1.5 cursor-pointer ${
            activeTab === 'actionPlan'
              ? 'bg-white dark:bg-slate-800 text-[#2563EB] dark:text-blue-400 shadow-2xs'
              : 'text-[#334155] dark:text-slate-400 hover:text-[#0F172A] dark:hover:text-white'
          }`}
        >
          <TrendingUp className="w-3.5 h-3.5" />
          <span>Priority Fixes</span>
        </button>
      </div>

      {/* Tab Content 1: Overview (Strengths & Gaps) */}
      {activeTab === 'overview' && (
        <div className="grid md:grid-cols-2 gap-5">
          
          {/* Key Strengths */}
          <div className="bg-white dark:bg-[#0f0f0f] border border-slate-200 dark:border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center space-x-2 text-emerald-700 dark:text-emerald-400">
              <CheckCircle2 className="w-4 h-4 shrink-0" />
              <h3 className="font-bold text-sm text-slate-900 dark:text-white">Demonstrated Strengths</h3>
            </div>
            <ul className="divide-y divide-slate-100 dark:divide-slate-800">
              {analysis.keyStrengths.map((strength, idx) => (
                <li key={idx} className="py-2.5 text-xs text-slate-700 dark:text-slate-300 leading-relaxed flex items-start space-x-2">
                  <span className="text-emerald-600 font-bold">•</span>
                  <span>{strength}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Critical Gaps */}
          <div className="bg-white dark:bg-[#0f0f0f] border border-slate-200 dark:border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center space-x-2 text-rose-700 dark:text-rose-400">
              <AlertTriangle className="w-4 h-4 shrink-0" />
              <h3 className="font-bold text-sm text-slate-900 dark:text-white">Identified Gaps & Optimization Risks</h3>
            </div>
            <ul className="divide-y divide-slate-100 dark:divide-slate-800">
              {analysis.criticalGaps.map((gap, idx) => (
                <li key={idx} className="py-2.5 text-xs text-slate-700 dark:text-slate-300 leading-relaxed flex items-start space-x-2">
                  <span className="text-rose-600 font-bold">•</span>
                  <span>{gap}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {/* Tab Content 2: ATS Compliance Checks */}
      {activeTab === 'atsChecks' && (
        <div className="bg-white dark:bg-[#0f0f0f] border border-slate-200 dark:border-slate-800 rounded-xl p-5 space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 dark:border-slate-800 pb-3">
            <div>
              <h3 className="font-bold text-sm text-slate-900 dark:text-white">ATS Parsing & Formatting Standards</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Evaluating against standard recruitment parser requirements
              </p>
            </div>

            {/* Filter pills */}
            <div className="flex items-center space-x-1">
              {(['all', 'warning', 'fail', 'pass'] as const).map((filter) => (
                <button
                  key={filter}
                  onClick={() => setAtsFilter(filter)}
                  className={`px-2.5 py-1 rounded text-xs font-semibold capitalize transition-colors cursor-pointer ${
                    atsFilter === filter
                      ? 'bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900'
                      : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'
                  }`}
                >
                  {filter}
                </button>
              ))}
            </div>
          </div>

          <div className="divide-y divide-slate-100 dark:divide-slate-800">
            {filteredAtsChecks.map((check, idx) => (
              <div key={idx} className="py-3 flex flex-col sm:flex-row sm:items-start justify-between gap-3">
                <div className="space-y-1 flex-1">
                  <div className="flex items-center space-x-2">
                    <span className="font-bold text-xs text-slate-900 dark:text-white">{check.category}</span>
                    <span className={`px-2 py-0.2 rounded text-[10px] font-bold uppercase ${
                      check.status === 'pass'
                        ? 'bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800'
                        : check.status === 'warning'
                        ? 'bg-amber-50 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300 border border-amber-200 dark:border-amber-800'
                        : 'bg-rose-50 dark:bg-rose-950/60 text-rose-700 dark:text-rose-300 border border-rose-200 dark:border-rose-800'
                    }`}>
                      {check.status}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-slate-300">{check.detail}</p>
                  {check.recommendation && (
                    <div className="bg-slate-50 dark:bg-[#161616] border border-slate-200 dark:border-slate-700 p-2.5 rounded text-[11px] text-slate-800 dark:text-slate-200 font-medium mt-1">
                      <strong>Fix:</strong> {check.recommendation}
                    </div>
                  )}
                </div>

                <div className="shrink-0 pt-0.5">
                  {check.status === 'pass' && <CheckCircle2 className="w-4 h-4 text-emerald-600" />}
                  {check.status === 'warning' && <AlertTriangle className="w-4 h-4 text-amber-500" />}
                  {check.status === 'fail' && <XCircle className="w-4 h-4 text-rose-600" />}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tab Content 3: Section Review & Bullet Rewriter */}
      {activeTab === 'sections' && (
        <div className="space-y-4">
          {analysis.sections.map((section, idx) => (
            <div key={idx} className="bg-white dark:bg-[#0f0f0f] border border-slate-200 dark:border-slate-800 rounded-xl p-5 space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
                <h3 className="font-bold text-sm text-slate-900 dark:text-white">
                  {section.sectionName}
                </h3>
                <span className={`px-2 py-0.2 rounded text-xs font-semibold border ${
                  section.score >= 80
                    ? 'bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800'
                    : section.score >= 60
                    ? 'bg-amber-50 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800'
                    : 'bg-rose-50 dark:bg-rose-950/60 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800'
                }`}>
                  Section Score: {section.score}%
                </span>
              </div>

              {/* Feedback Points */}
              <div className="grid md:grid-cols-2 gap-3">
                <div className="bg-slate-50 dark:bg-[#161616] p-3 rounded-lg border border-slate-200 dark:border-slate-700 space-y-1.5">
                  <span className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Observations:</span>
                  <ul className="space-y-1 text-xs text-slate-700 dark:text-slate-300">
                    {section.feedback.map((f, i) => (
                      <li key={i} className="flex items-start space-x-1.5">
                        <span className="text-slate-400">•</span>
                        <span>{f}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="bg-slate-50 dark:bg-[#161616] p-3 rounded-lg border border-slate-200 dark:border-slate-700 space-y-1.5">
                  <span className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Recommended Enhancements:</span>
                  <ul className="space-y-1 text-xs text-slate-700 dark:text-slate-300">
                    {section.suggestions.map((s, i) => (
                      <li key={i} className="flex items-start space-x-1.5">
                        <span className="text-emerald-600">•</span>
                        <span>{s}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Bullet Rewrites */}
              {section.rewrites && section.rewrites.length > 0 && (
                <div className="space-y-2.5 pt-2">
                  <h4 className="text-xs font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider">
                    High-Impact Bullet Rewrites
                  </h4>

                  {section.rewrites.map((rewrite, rIdx) => (
                    <div key={rIdx} className="bg-slate-50 dark:bg-[#161616] p-3.5 rounded-lg border border-slate-200 dark:border-slate-700 space-y-2">
                      <div>
                        <span className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase">Original Bullet:</span>
                        <p className="text-xs text-slate-500 dark:text-slate-400 line-through mt-0.5">{rewrite.original}</p>
                      </div>

                      <div className="bg-white dark:bg-[#0f0f0f] p-3 rounded border border-slate-200 dark:border-slate-700 space-y-1">
                        <div className="flex items-center justify-between">
                          <span className="text-[10px] font-bold text-emerald-700 dark:text-emerald-400 uppercase">
                            Quantified Rewrite:
                          </span>
                          <button
                            onClick={() => handleCopy(rewrite.suggested, `rewrite_${idx}_${rIdx}`)}
                            className="p-1 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white rounded text-xs flex items-center space-x-1 transition-colors font-medium cursor-pointer"
                          >
                            {copiedIndex === `rewrite_${idx}_${rIdx}` ? (
                              <Check className="w-3.5 h-3.5 text-emerald-600" />
                            ) : (
                              <Copy className="w-3.5 h-3.5" />
                            )}
                            <span className="text-[10px]">Copy</span>
                          </button>
                        </div>
                        <p className="text-xs text-slate-900 dark:text-slate-100 font-semibold">{rewrite.suggested}</p>
                      </div>

                      <p className="text-[11px] text-slate-600 dark:text-slate-400">
                        <strong>Reasoning:</strong> {rewrite.reasoning}
                      </p>
                    </div>
                  ))}
                </div>
              )}

            </div>
          ))}
        </div>
      )}

      {/* Tab Content 4: Skills Cloud */}
      {activeTab === 'skills' && (
        <div className="bg-white dark:bg-[#0f0f0f] border border-slate-200 dark:border-slate-800 rounded-xl p-5 space-y-5">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 dark:border-slate-800 pb-3">
            <div>
              <h3 className="font-bold text-sm text-slate-900 dark:text-white">Detected Skills Matrix</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Keywords identified in the resume text for ATS categorization
              </p>
            </div>

            <div className="relative">
              <Search className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                value={skillSearch}
                onChange={(e) => setSkillSearch(e.target.value)}
                placeholder="Search skills..."
                className="pl-7 pr-3 py-1 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded text-xs text-slate-900 dark:text-slate-100 focus:outline-none focus:border-slate-600 font-medium"
              />
            </div>
          </div>

          <div className="space-y-4">
            <div>
              <h4 className="text-xs font-bold text-slate-700 dark:text-slate-300 mb-2 uppercase tracking-wider">
                Technical Skills & Tools
              </h4>
              <div className="flex flex-wrap gap-1.5">
                {analysis.detectedSkills.technical
                  .filter((sk) => sk.toLowerCase().includes(skillSearch.toLowerCase()))
                  .map((sk, i) => (
                    <span key={i} className="px-2.5 py-1 bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 border border-slate-200 dark:border-slate-700 rounded text-xs font-medium">
                      {sk}
                    </span>
                  ))}
              </div>
            </div>

            <div>
              <h4 className="text-xs font-bold text-slate-700 dark:text-slate-300 mb-2 uppercase tracking-wider">
                Frameworks, Cloud & Infrastructure
              </h4>
              <div className="flex flex-wrap gap-1.5">
                {analysis.detectedSkills.toolsAndFrameworks
                  .filter((sk) => sk.toLowerCase().includes(skillSearch.toLowerCase()))
                  .map((sk, i) => (
                    <span key={i} className="px-2.5 py-1 bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 border border-slate-200 dark:border-slate-700 rounded text-xs font-medium">
                      {sk}
                    </span>
                  ))}
              </div>
            </div>

            <div>
              <h4 className="text-xs font-bold text-slate-700 dark:text-slate-300 mb-2 uppercase tracking-wider">
                Management, Leadership & Communication
              </h4>
              <div className="flex flex-wrap gap-1.5">
                {analysis.detectedSkills.soft
                  .filter((sk) => sk.toLowerCase().includes(skillSearch.toLowerCase()))
                  .map((sk, i) => (
                    <span key={i} className="px-2.5 py-1 bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 border border-slate-200 dark:border-slate-700 rounded text-xs font-medium">
                      {sk}
                    </span>
                  ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tab Content 5: Priority Fixes */}
      {activeTab === 'actionPlan' && (
        <div className="bg-white dark:bg-[#0f0f0f] border border-slate-200 dark:border-slate-800 rounded-xl p-5 space-y-4">
          <div className="border-b border-slate-100 dark:border-slate-800 pb-3">
            <h3 className="font-bold text-sm text-slate-900 dark:text-white">
              Prioritized Optimization Action Plan
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Address these items in order of estimated scoring impact
            </p>
          </div>

          <div className="space-y-2.5">
            {analysis.actionableNextSteps.map((step, i) => (
              <div key={i} className="flex items-start space-x-3 bg-slate-50 dark:bg-[#161616] p-3.5 rounded-lg border border-slate-200 dark:border-slate-700">
                <span className="flex items-center justify-center w-6 h-6 rounded bg-slate-900 dark:bg-slate-100 text-white dark:text-slate-900 font-bold text-xs shrink-0 mt-0.5">
                  {i + 1}
                </span>
                <div className="space-y-0.5">
                  <p className="text-xs text-slate-800 dark:text-slate-200 font-semibold leading-relaxed">
                    {step}
                  </p>
                  <span className="text-[10px] font-semibold text-emerald-600 dark:text-emerald-400">
                    Estimated Impact: +{Math.max(3, 8 - i * 2)} ATS Points
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

    </div>
  );
};
